# Generated by Django 3.2.7 on 2021-12-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='aadhar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_phone',
            field=models.IntegerField(),
        ),
    ]
