# Generated by Django 3.2.8 on 2021-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0003_citizen_isolation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Self_Assesment_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('vaccine', models.BooleanField()),
                ('past_covid', models.BooleanField()),
                ('roaming', models.BooleanField()),
            ],
        ),
    ]
