# Generated by Django 3.2.8 on 2021-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0004_self_assesment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='profile_photo',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
