# Generated by Django 3.2.8 on 2021-12-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0007_hospital_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='avail_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoviSafe.hospital'),
        ),
    ]
