# Generated by Django 3.2.8 on 2021-12-18 14:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0008_citizen_avail_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='slot_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None),
        ),
    ]
