# Generated by Django 3.2.8 on 2021-12-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0009_alter_hospital_slot_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='avail_slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='avail_slot',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='slot_date',
        ),
        migrations.AddField(
            model_name='citizen',
            name='avail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoviSafe.avail_slot'),
        ),
    ]
