# Generated by Django 3.2.7 on 2021-12-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0010_auto_20211218_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField()),
                ('deceased', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('active', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='stats_display',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CoviSafe.stats'),
        ),
    ]
