# Generated by Django 3.2.7 on 2021-12-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoviSafe', '0011_auto_20211218_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='stats_display',
        ),
        migrations.DeleteModel(
            name='stats',
        ),
    ]
